---
title: "R Notebook"
output:
  html_notebook:
    theme: united
    highlight: tango
---

```{r setup}

knitr::opts_knit$set(root.dir = "C:/Users/dgallen/Desktop/Projects/OD balance/OD")
getwd()
library(readxl)
library(reshape2)
```

```{r load data}
# rm(list = ls())

read_excel_sheets <- function(file){
  
  sheets <- readxl::excel_sheets("TablePercents_split.xlsx")
  x <- lapply(sheets, function(x) readxl::read_xlsx("TablePercents_split.xlsx", sheet = x,col_names = FALSE, na = 'NA'))
  x <- lapply(x, as.matrix)
  names(x) <- sheets
  x
}

percent_list <- read_excel_sheets("TablePercents_split.xlsx")

InputVolume <- read.csv('InputVols.csv')

InputVol <- list()

for(n in 1:length(levels(as.factor(InputVolume$Table)))) {

  g <- InputVolume[InputVolume$Table==n,]

  tab <- split(g,paste("TP",g$TimePeriod,sep=''))

  InputVol[[n]] <- tab
}


Target <- read.csv('TargetVols.csv')

Targets <- list()

for(n in 1:length(levels(as.factor(Target$Table)))) {

  g <- Target[Target$Table==n,]

  tab <- split(g,paste("TP",g$TimePeriod,sep=''))

  Targets[[n]] <- tab
}
```

```{r OD function}

OD_Bal <- function(volume_list,percent,target_list){
  
  if(nrow(percent) != 1){
  
  table_list <- list()
  
  for(i in c(1:length(volume_list))){
    
    volume <- volume_list[[i]]$InputVol
    target <- target_list[[i]]$Target
    
    # col_fix <- function(volume,percent,target) {
    
    col_no <- ncol(percent)
    row_no <- nrow(percent)
    
    ## setup a matrix to hold the results
    dat <- matrix(nrow = row_no, ncol = col_no)
    
    
    for(n in c(1:col_no)) {
      
      x <- percent[,n]
      
      cnt <- 1
      # itr <- 1
      
      ##repeat loop will stop on given if command - see below
      repeat {
        x[cnt] <- ifelse(sum(x*volume, na.rm = T)-target[n] < 0,
                         (ifelse(x[cnt] >= .99,
                                 x[cnt],x[cnt] + .01)),
                         (ifelse(x[cnt] <= .01,
                                 x[cnt],x[cnt] - .01)))
        
        cnt <- ifelse(cnt == row_no, 1, cnt + 1)
        # itr <- itr + 1
        
        ##if total cars are less than 5 "break" the loop
        if(abs(sum(x * volume, na.rm = T) - target[n]) < 6) {
          break
        }
      }
      dat[,n] <- x
    }
    
    dat_2 <- dat
    
    for(n in c(1:row_no)){
    
    y <- dat_2[n,]

    repeat {
      
      col_diff <- colSums(apply(dat_2,2,function(x) x*volume), na.rm = TRUE)-target
      row_sum <- sum(y, na.rm = TRUE)
      
      index1 <- 1
      
      repeat {
        
        min_col <- match(sort(col_diff)[index1],col_diff)
        index1 <- index1 + 1
        
      log1 <- !is.na(y[min_col]) & y[min_col] >= 0 & y[min_col] <= 0.99
      log2 <- !is.na(y[min_col]) & y[min_col] == 1
      
      if(log1 | log2 ){
          break
        }
      }
      
      index2 <- 1
      
      repeat {
        
        max_col <- match(sort(col_diff,decreasing = TRUE)[index2],col_diff)
        index2 <- index2 + 1
        
        log1 <- !is.na(y[max_col]) & y[max_col] >= 0.01 & y[max_col] <= 1
        log2 <- !is.na(y[max_col]) & y[max_col] == 1
        
        if(log1 | log2 ){
          break
        }
      }
      
      x <- ifelse(row_sum < 1, 
                  min_col, 
                  max_col)
      
      y[x] <- ifelse(sum(y, na.rm = TRUE) >= 0.99 & sum(y, na.rm = TRUE) <= 1.01,
                     
                     y[x],
                     
                     ifelse(sum(y, na.rm = TRUE) < 1, 
                            y[x] + .001,
                            y[x] - .001))
      
      dat_2[n,] <- y
      
      if(sum(y,na.rm = TRUE) >= 0.99 & sum(y,na.rm = TRUE) <= 1.01) {
        break
        }
      }
    }
    
    # row_fix <- percent_fix(col_fix = col_fix, target = target,volume = volume)
    # 
    # porportion <- function(percent,volume) {
    
    vol_new <- apply(dat_2,2,function(x) x * volume)
    
    # round(apply(dat,2,function(x) x * volume),0)
    
    sum_col <- colSums(vol_new, na.rm = TRUE)
    
    porportion <- mapply(function(x) {vol_new[,x]/sum_col[x]},
                         x = c(1:ncol(vol_new)))
    
    col_diff <- sum_col-target
    
    prop_diff <- mapply(function(x) {porportion[,x]*col_diff[x]},
                        x = c(1:ncol(porportion)))
    
    diff <- mapply(function(x) {ifelse(is.na(prop_diff[,x]/volume),prop_diff[,x],prop_diff[,x]/volume)},
                   x = c(1:ncol(prop_diff)))
    
    k <- dat_2 - diff
    
    dat_final <- k
  dat_final[,ncol(dat_final)] <- k[,ncol(k)] - (rowSums(k, na.rm = TRUE)-1)
  
  table_list[[i]] <- dat_final 
  
  }
  return(table_list)
  }
  print('One row of data - target / volume')
  
  table_list <- list()
  
  for(i in c(1:length(volume_list))){
    
    volume <- volume_list[[i]]$InputVol
    target <- target_list[[i]]$Target
    
    dat_final <- target / volume
    
    table_list[[i]] <- dat_final
  }
  return(table_list)
}


```

```{r table 1}

vol_1 <- InputVol[[1]]
tar_1 <- Targets[[1]]
percent_1 <- percent_list[[1]]

table1 <- OD_Bal(volume_list = vol_1, percent = percent_1, target_list = tar_1)

for(i in c(1:20)){
print(round(sum(colSums(apply(table1[[i]],2,function(x) x*vol_1[[i]]$InputVol), na.rm = TRUE)-tar_1[[i]]$Value),4))

print(rowSums(table1[[i]],na.rm = TRUE))

}

```

```{r table 2}
vol_2 <- InputVol[[2]]
tar_2 <- Targets[[2]]
percent_2 <- percent_list[[2]]

table2 <- OD_Bal(volume_list = vol_2, percent = percent_2, target_list = tar_2)

for(i in c(1:20)){
print(round(sum(colSums(apply(table2[[i]],2,function(x) x*vol_2[[i]]$InputVol), na.rm = TRUE)-tar_2[[i]]$Value),4))

print(rowSums(table2[[i]],na.rm = TRUE))
}
```

```{r table 3}
vol_3 <- InputVol[[3]]
tar_3 <- Targets[[3]]
percent_3 <- percent_list[[3]]

table3 <- OD_Bal(volume_list = vol_3, percent = percent_3, target_list = tar_3)

for(i in c(1:20)){
print(round(sum(colSums(apply(table3[[i]],2,function(x) x*vol_3[[i]]$InputVol), na.rm = TRUE)-tar_3[[i]]$Value),5))

print(rowSums(table3[[i]],na.rm = TRUE))
}

```

```{r table 4}

vol_4 <- InputVol[[4]]
tar_4 <- Targets[[4]]
percent_4 <- percent_list[[4]]

table4 <- OD_Bal(volume_list = vol_4, percent = percent_4, target_list = tar_4)

for(i in c(1:20)){
print(round(sum(colSums(apply(table4[[i]],2,function(x) x*vol_4[[i]]$InputVol), na.rm = TRUE)-tar_4[[i]]$Value),4))

print(rowSums(table4[[i]],na.rm = TRUE))
}

```

```{r table 5}

vol_5 <- InputVol[[5]]
tar_5 <- Targets[[5]]
percent_5 <- percent_list[[5]]

table5 <- OD_Bal(volume_list = vol_5, percent = percent_5, target_list = tar_5)

for(i in c(1:20)){
print(round(sum(colSums(apply(table5[[i]],2,function(x) x*vol_5[[i]]$InputVol), na.rm = TRUE)-tar_5[[i]]$Value),5))

print(rowSums(table5[[i]],na.rm = TRUE))
}

```

```{r table 6}

vol_6 <- InputVol[[6]]
tar_6 <- Targets[[6]]
percent_6 <- percent_list[[6]]

table6 <- OD_Bal(volume_list = vol_6, percent = percent_6, target_list = tar_6)

for(i in c(1:20)){
print(round(sum(colSums(apply(table6[[i]],2,function(x) x*vol_6[[i]]$InputVol), na.rm = TRUE)-tar_6[[i]]$Value),6))

print(rowSums(table6[[i]],na.rm = TRUE))
}

```

```{r table 7}

vol_7 <- InputVol[[7]]
tar_7 <- Targets[[7]]
percent_7 <- percent_list[[7]]

table7 <- OD_Bal(volume_list = vol_7, percent = percent_7, target_list = tar_7)

for(i in c(1:20)){
print(round(sum(colSums(apply(table7[[i]],2,function(x) x*vol_7[[i]]$InputVol), na.rm = TRUE)-tar_7[[i]]$Value),7))

print(rowSums(table7[[i]],na.rm = TRUE))
}

```

```{r table 8}

vol_8 <- InputVol[[8]]
tar_8 <- Targets[[8]]
percent_8 <- percent_list[[8]]

table8 <- OD_Bal(volume_list = vol_8, percent = percent_8, target_list = tar_8)

for(i in c(1:20)){
print(round(sum(colSums(apply(table8[[i]],2,function(x) x*vol_8[[i]]$InputVol), na.rm = TRUE)-tar_8[[i]]$Value),8))

print(rowSums(table8[[i]],na.rm = TRUE))
}

```

```{r table 9}

vol_9 <- InputVol[[9]]
tar_9 <- Targets[[9]]
percent_9 <- percent_list[[9]]

table9 <- OD_Bal(volume_list = vol_9, percent = percent_9, target_list = tar_9)

for(i in c(1:20)){
print(round(sum(colSums(apply(table9[[i]],2,function(x) x*vol_9[[i]]$InputVol), na.rm = TRUE)-tar_9[[i]]$Value),9))

print(rowSums(table9[[i]],na.rm = TRUE))
}

```

```{r table 10}

vol_10 <- InputVol[[10]]
tar_10 <- Targets[[10]]
percent_10 <- percent_list[[10]]

table10 <- OD_Bal(volume_list = vol_10, percent = percent_10, target_list = tar_10)

for(i in c(1:20)){
print(round(sum(colSums(apply(table10[[i]],2,function(x) x*vol_10[[i]]$InputVol), na.rm = TRUE)-tar_10[[i]]$Value),10))

print(rowSums(table10[[i]],na.rm = TRUE))
}

```

```{r table 11}

vol_11 <- InputVol[[11]]
tar_11 <- Targets[[11]]
percent_11 <- percent_list[[11]]

table11 <- OD_Bal(volume_list = vol_11, percent = percent_11, target_list = tar_11)

print(lapply(table11,sum))
```